id: IE045EED7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T04:43:10+00:00'
last_modified: '2022-06-08T06:28:06.058255+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14736
  title: རོགས་མཐུན་ཁུ་བྱུག་དབྱངས་སྙན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    2C55:
      image_group_id: I2PD17907
      title: ''
      total_pages: 364
      order: 1
      base_file: 2C55.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
