id: P006732
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:19:51.649256
source_metadata:
  id: bdr:W1KG14736
  title: རོགས་མཐུན་ཁུ་བྱུག་དབྱངས་སྙན།
  author: ''
  volumes:
    ac7d5a69892c423397ac16fead0cb3ad:
      image_group_id: I2PD17907
      title: ''
      volume_number: 1
      total_pages: 364
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
